---
- hosts: all
  tasks:
  - name: get-cli
    command: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
  - name: create-jobs 
    shell: "java -jar jenkins-cli.jar -s http://localhost:8080/ create-job {{item}} < {{item}}.xml"
    with_lines: cat configs.txt
