---
- hosts: all
  tasks:
  - name: delete-jobs 
    shell: "java -jar jenkins-cli.jar -s http://localhost:8080/ delete-job {{item}}"
    with_lines: cat configs.txt
  - name: delete-files
    shell: "rm -rf tool_recommender_bot* jenkins-cli.jar configs.txt"